// examples/web-router/routes/(components)/Echo@widget.tsx
import { useState } from 'react';
import { echo } from '../(actions)/actions@action';

export default () => {
  const [log, setLog] = useState('');
  return (
    <div>
      <button
        onClick={async () => {
          const value = await echo('hello world');
          setLog(JSON.stringify(value, null, 2));
        }}>
        echo
      </button>
      <pre>{log}</pre>
    </div>
  );
};

// examples/vue/routes/action/Echo@widget.vue
<script setup lang="ts">
import { ref } from 'vue';
import { echo } from './functions@action';
import './styles.css';

const inputValue = ref('');
const log = ref('');

const handleClick = async () => {
  const value = await echo(inputValue.value);
  log.value = JSON.stringify(value, null, 2);
};
</script>

<template>
  <div>
    <input type="text" v-model="inputValue" />

    <button @click="handleClick">
      echo
    </button>

    <div v-if="log" class="log">
      <p>
        This is the content returned from the server function. Please view
        the network request in the console.
      </p>
      <pre>{{ log }}</pre>
    </div>
  </div>
</template>
