// examples/routes/_components/Github@widget.tsx
import React, { useState } from "react";
import { useWidgetState } from "@web-widget/react";

interface GitHubUserData {
  name: string;
  location: string;
  avatar_url: string;
}

interface Props {
  username: string;
}

const useFetchGithub = (username: string): GitHubUserData => {
  const url = `https://api.github.com/users/${username}`;
  const cacheKey = url + "@react";
  const data = useWidgetState(cacheKey, async () => {
    console.log("[github]", "fetch..");

    const resp = await fetch(url);
    if (!resp.ok) {
      throw new Error(`[github] ${JSON.stringify(await resp.json())}`);
    }
    const { name, location, avatar_url } = await resp.json();
    return { name, location, avatar_url, "react@</script>": Date.now() };
  });

  return data;
};

const WidgetComponent: React.FC<Props> = ({ username }: Props) => {
  console.log("react", Date.now());
  const data = useFetchGithub(username);
  const [show, setShow] = useState(false);

  return (
    <div>
      <button onClick={() => setShow(true)}>React: Show Github Info</button>
      <pre style={{ display: show ? "block" : "none" }}>
        {JSON.stringify(data, null, 2)}
      </pre>
    </div>
  );
};

export default WidgetComponent;

// examples/routes/(vue3)/Github@widget.vue
<script setup lang="ts">
console.log("vue", Date.now());
import { useWidgetState } from '@web-widget/vue';
import { ref } from 'vue';

const props = defineProps({
    username: String,
});

const url = `https://api.github.com/users/${props.username}`;
const cacheKey = url + '@vue';

const data = await useWidgetState(cacheKey, async () => {
    console.log("[github]", "fetch..");
    const resp = await fetch(url);
    if (!resp.ok) {
        throw new Error(`[github] ${JSON.stringify(await resp.json())}`);
    }
    const { name, location, avatar_url } = await resp.json();
    return { name, location, avatar_url, ["vue@</" + "script>"]: (Date.now()) };
})

const show = ref(false);
</script>

<template>
    <div>
        <button @click="show = true">Vue: Show Github Info</button>
        <pre v-show="show">{{ data }}</pre>
    </div>
</template>
