// examples/vue/routes/greet/[name]@route.vue
<script setup lang="ts">
import { defineMeta } from '@web-widget/helpers';
import BaseLayout from '../(components)/BaseLayout.vue';

interface Params {
  name: string;
}

defineOptions({
  meta: defineMeta({
    title: 'Dynamic routes - Web Widget',
  }),
});

const { params } = defineProps<{ params: Params }>();
</script>

<template>
  <BaseLayout>
    <h1>Dynamic routes</h1>
    <p>Greetings to you, {{ params.name }}!</p>
    <p>
      <a href="/greet/react">react</a>
    </p>
    <p>
      <a href="/greet/vue">vue</a>
    </p>
  </BaseLayout>
</template>

// examples/react/routes/greet/[name]@route.tsx
import { defineRouteComponent, defineMeta } from '@web-widget/helpers';
import BaseLayout from '../(components)/BaseLayout.tsx';

interface Params {
  name: string;
}

export const meta = defineMeta({
  title: 'Dynamic routes - Web Widget',
});

export default defineRouteComponent<null, Params>(function Page({ params }) {
  const { name } = params;
  return (
    <BaseLayout>
      <h1>Dynamic routes</h1>
      <p>Greetings to you, {name}!</p>
      <p>
        <a href="/greet/react">react</a>
      </p>
      <p>
        <a href="/greet/vue">vue</a>
      </p>
    </BaseLayout>
  );
});
