// playgrounds/router/routes/streaming/preact/PageHeader.tsx
/** @jsxImportSource preact */
import type { ComponentChildren } from 'preact';

export default function PageHeader(props: {
  title: string;
  description?: string;
  children?: ComponentChildren;
}) {
  return (
    <header class="ds-page-header">
      <h1>{props.title}</h1>
      {props.description && <p class="ds-description">{props.description}</p>}
      {props.children}
    </header>
  );
}

// playgrounds/router/routes/frameworks/svelte/PageHeader.svelte
<script lang="ts">
  let { title, description, children }: { title: string; description?: string; children?: import('svelte').Snippet } = $props();
</script>

<header class="ds-page-header">
  <h1>{title}</h1>
  {#if description}<p class="ds-description">{description}</p>{/if}
  {@render children?.()}
</header>
