// playgrounds/router/routes/streaming/preact/Section.tsx
/** @jsxImportSource preact */
import type { ComponentChildren } from 'preact';

export default function Section(props: {
  title: string;
  description?: string;
  children: ComponentChildren;
}) {
  return (
    <section class="ds-section">
      <h2>{props.title}</h2>
      {props.description && <p class="ds-description">{props.description}</p>}
      {props.children}
    </section>
  );
}

// playgrounds/router/routes/frameworks/svelte/Section.svelte
<script lang="ts">
  let { title, description, children }: { title: string; description?: string; children: import('svelte').Snippet } = $props();
</script>

<section class="ds-section">
  <h2>{title}</h2>
  {#if description}<p class="ds-description">{description}</p>{/if}
  {@render children()}
</section>
