// playgrounds/router/routes/(components)/react/Counter@widget.tsx
import { useState } from 'react';
import styles from '~/routes/(css)/counter.module.css';

export default function Counter({
  count: initialCount = 0,
}: {
  count?: number;
}) {
  const [count, setCount] = useState(initialCount);
  return (
    <button className={styles.button} onClick={() => setCount(count + 1)}>
      React count is {count}
    </button>
  );
}

// playgrounds/router/routes/(vue3)/frameworks/vue3/Counter@widget.vue
<script setup lang="ts">
import { ref } from 'vue';
import styles from '~/routes/(css)/counter.module.css';

const props = withDefaults(defineProps<{ count?: number }>(), { count: 0 });
const count = ref(props.count);
</script>

<template>
  <button :class="styles.button" @click="count += 1">
    Vue 3 count is {{ count }}
  </button>
</template>

<style scoped>
button {
  --vue-scoped-owner: vue3;
  --vue-scoped-version: 1;
}
</style>
