// playgrounds/router/routes/(vue3)/BaseLayout.vue
<script setup lang="ts">
import { onMounted } from 'vue';
import '../(css)/base-layout.css';
import '../(css)/ui.css';
import { widget } from '@web-widget/vue/adapter';

const Menu = widget(() => import('../(components)/Menu@widget.ts'));

onMounted(() => {
  const path = location.pathname;
  document.querySelectorAll('aside a[href]').forEach((a) => {
    if (a.getAttribute('href') === path) {
      a.setAttribute('aria-current', 'page');
    }
  });
});
</script>
<template>
  <header class="site-header">
    <h1>Web Router Playground</h1>
  </header>
  <div class="container">
    <aside>
      <Menu :widget="{ serverOnly: true }" />
    </aside>
    <main><slot></slot></main>
  </div>
  <footer>
    <p>This is a footer</p>
  </footer>
</template>

// playgrounds/router/routes/(components)/BaseLayout.tsx
import '../(css)/base-layout.css';
import '../(css)/ui.css';

import type { ComponentProps } from 'react';
import { widget } from '@web-widget/react/adapter';

const Menu = widget(() => import('./Menu@widget.ts'));

export default function BaseLayout({ children }: ComponentProps<any>) {
  return (
    <>
      <header className="site-header">
        <h1>Web Router Playground</h1>
      </header>
      <div className="container">
        <aside>
          <Menu widget={{ serverOnly: true }} />
        </aside>
        <main>{children}</main>
      </div>
      <footer>
        <p>This is a footer</p>
      </footer>
      <script
        dangerouslySetInnerHTML={{
          __html: `(function(){var p=location.pathname;document.querySelectorAll('aside a[href]').forEach(function(a){if(a.getAttribute('href')===p)a.setAttribute('aria-current','page')})})();`,
        }}
      />
    </>
  );
}
