// examples/web-router/routes/(vue3)/Wait@widget.vue
<script setup lang="ts">
import { ref } from 'vue';
const props = defineProps(['id']);

const random = (max: number, min: number) =>
  Math.floor(Math.random() * (max - min + 1) + min);
const fetchData = async (timeout = random(900, 2900)) =>
  await new Promise((resolve) =>
    setTimeout(() => resolve(`Hello World`), timeout)
  );
const data = (await fetchData()) as string;
</script>

<template>
  <div class="box">Vue {{ id }}: {{ data }}</div>
</template>

<style scoped>
.box {
  background: linear-gradient(315deg, #42d392 25%, #647eff);
  color: #fff;
  padding: 20px;
}
</style>

// playgrounds/router/routes/(components)/Wait@widget.tsx
const random = (max: number, min: number) =>
  Math.floor(Math.random() * (max - min + 1) + min);
const fetchData = async (timeout = random(900, 2900)) =>
  await new Promise((resolve) =>
    setTimeout(() => resolve(`Hello World`), timeout)
  );

export default (async function Wait({ id }: { id: string }) {
  const data = (await fetchData()) as string;
  return (
    <div
      style={{
        background: 'linear-gradient(315deg,#42d392 25%,#0074a6)',
        color: '#FFF',
        padding: '20px',
      }}>
      React {id}: {data}
    </div>
  );
} as unknown as React.FunctionComponent<any>);
