// examples/vue/routes/action/Echo@widget.vue
<script setup lang="ts">
import { ref } from 'vue';
import { echo } from './functions@action';
import './styles.css';

const inputValue = ref('');
const log = ref('');

const handleClick = async () => {
  const value = await echo(inputValue.value);
  log.value = JSON.stringify(value, null, 2);
};
</script>

<template>
  <div>
    <input type="text" v-model="inputValue" />

    <button @click="handleClick">
      echo
    </button>

    <div v-if="log" class="log">
      <p>
        This is the content returned from the server function. Please view
        the network request in the console.
      </p>
      <pre>{{ log }}</pre>
    </div>
  </div>
</template>

// examples/react/routes/action/Echo@widget.tsx
import { useState } from 'react';
import { echo } from './functions@action';
import './styles.css';

export default () => {
  const [log, setLog] = useState('');
  const [inputValue, setInputValue] = useState('');

  return (
    <>
      <input
        type="text"
        value={inputValue}
        onChange={(e) => setInputValue(e.target.value)}
      />

      <button
        onClick={async () => {
          // NOTE: This is a client-side call to the server-side function
          const value = await echo(inputValue);
          setLog(JSON.stringify(value, null, 2));
        }}>
        echo
      </button>

      {log && (
        <div className="log">
          <p>
            This is the content returned from the server function. Please view
            the network request in the console.
          </p>
          <pre>{log}</pre>
        </div>
      )}
    </>
  );
};
