// examples/examples/components/Menu.tsx
export default function Menu() {
  return (
    <>
      <ul>
        <li>
          <a href="/">🏠</a>
        </li>
        <li>
          <a href="/hello-world">Hello wrold</a>
        </li>
        <li>
          <a href="/dynamic-routes/@web-widget">Dynamic routes</a>
        </li>
        <li>
          <a href="/adding-interactivity">Adding interactivity</a>
        </li>
        <li>
          <a href="/react-and-vue">Using react and vue together</a>
        </li>
        <li>
          <a href="/custom-handlers">Custom handlers</a>
        </li>
        <li>
          <a href="/client-only-component">Client only component</a>
        </li>
        <li>
          <a href="/fetching-data">Fetching data</a>
        </li>
        <li>
          <a href="/style">Styling</a>
        </li>
        <li>
          <a href="/meta">Meta</a>
        </li>
        <li>
          <a href="/form">Form submissions</a>
        </li>
        <li>
          <a href="/fallback">Error handling</a>
        </li>
        <li>
          <a href="/streaming">Streaming</a>
        </li>
        <li>
          <a href="/experimental-async-component">Async component</a>
        </li>
        <li>
          <a target="_blank" href="/lit-html-template">
            Lit html template
          </a>
        </li>
        <li>
          <a target="_blank" href="/api/hello-world">
            Api route
          </a>
        </li>
      </ul>
    </>
  );
}

// examples/examples/widgets/Menu.vue
<template>
  <ul class="menu">
    <li>
      <a href="/">🏠</a>
    </li>
    <li>
      <a href="/hello-world">Hello wrold</a>
    </li>
    <li>
      <a href="/dynamic-routes/@web-widget">Dynamic routes</a>
    </li>
    <li>
      <a href="/adding-interactivity">Adding interactivity</a>
    </li>
    <li>
      <a href="/react-and-vue">Using react and vue together</a>
    </li>
    <li>
      <a href="/custom-handlers">Custom handlers</a>
    </li>
    <li>
      <a href="/client-only-component">Client only component</a>
    </li>
    <li>
      <a href="/fetching-data">Fetching data</a>
    </li>
    <li>
      <a href="/style">Styling</a>
    </li>
    <li>
      <a href="/meta">Meta</a>
    </li>
    <li>
      <a href="/form">Form submissions</a>
    </li>
    <li>
      <a href="/fallback">Error handling</a>
    </li>
    <li><a href="/streaming">Streaming</a></li>
    <li>
      <a href="/experimental-async-component">Async component</a>
    </li>
    <li>
      <a target="_blank" href="/lit-html-template">
        Lit html template
      </a>
    </li>
    <li>
      <a target="_blank" href="/api/hello-world">
        Api route
      </a>
    </li>
  </ul>
</template>

<style scoped>
  .menu {
    color: cadetblue;
  }
</style>
