// playgrounds/widget/packages/vue2/App.vue
<script setup lang="ts">
import ReactCounter from '../react/Counter@widget.tsx';
import VueCounter from '../vue3/Counter@widget.vue';
import Vue2Counter from './Counter@widget.vue';
import { ref } from 'vue';

const count = ref(0);
</script>

<template>
  <div>
    <div>
      <a href="https://vitejs.dev" target="_blank">
        <img src="/vite.svg" class="logo" alt="Vite logo" />
      </a>
      <a href="https://vuejs.org/" target="_blank">
        <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
      </a>
    </div>
    <h1>Vite + Vue2</h1>
    <div>
      <h2>React component:</h2>
      <ReactCounter :count="3" />

      <h2>Vue3 component:</h2>
      <VueCounter :count="3" />

      <h2>Vue2 component:</h2>
      <Vue2Counter :count="3" />
    </div>
    <div class="card">
      <button type="button" @click="count++">count is {{ count }}</button>
    </div>
    <p>Edit <code>packages/vue2/App.vue</code> and save to test HMR</p>
  </div>
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}

.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}

.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// playgrounds/widget/packages/react/App.tsx
import { useState } from 'react';
import reactLogo from './assets/react.svg';
import viteLogo from '/vite.svg';
import './App.css';

import VueCounter from '../vue3/Counter@widget.vue?as=jsx';
import Vue2Counter from '../vue2/Counter@widget.vue?as=jsx';
import ReactCounter from './Counter@widget';

function App() {
  const [count, setCount] = useState(0);

  return (
    <div>
      <div>
        <a href="https://vitejs.dev" target="_blank" rel="noreferrer">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank" rel="noreferrer">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <div>
        <h2>React component:</h2>
        <ReactCounter count={3} />

        <h2>Vue3 component:</h2>
        <VueCounter count={3} />

        <h2>Vue2 component:</h2>
        <Vue2Counter count={3} />
      </div>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
      </div>
      <p>
        Edit <code>packages/react/App.tsx</code> and save to test HMR
      </p>
    </div>
  );
}

export default App;
