// playgrounds/router/routes/streaming/react/error@route.tsx
import { defineRouteComponent, defineRouteHandler } from '@web-widget/helpers';
import '~/routes/(css)/demo-states.css';
import BaseLayout from '~/routes/(components)/BaseLayout.js';
import { PageHeader, Section } from '~/routes/(components)/ui';
import ReactWaitDemo from '~/routes/(components)/Wait@widget.js';
import ReactFailDemo from '~/routes/(components)/Fail@widget.js';

const Loading = <div className="demo-loading">Loading..</div>;

const Error = (
  <div className="demo-error">Widget failed to render (error recovered)</div>
);

export const handler = defineRouteHandler({
  async GET(ctx) {
    return ctx.html(undefined, { renderer: { progressive: true } });
  },
});

export default defineRouteComponent(async function Page() {
  return (
    <BaseLayout>
      <PageHeader
        title="React: Streaming error"
        description="This page demonstrates streaming SSR error recovery. The failing widget is wrapped in an ErrorBoundary so the rest of the page stays functional."
      />

      <Section title="Normal widget (succeeds)">
        <ReactWaitDemo widget={{ fallback: Loading }} id="ok:0" />
      </Section>

      <Section title="Failing widget with differentiated fallback (loading vs error)">
        <ReactFailDemo
          widget={{ fallback: { pending: Loading, error: Error } }}
          id="fail:0"
        />
      </Section>

      <Section title="Another normal widget after the failure">
        <ReactWaitDemo widget={{ fallback: Loading }} id="ok:1" />
      </Section>
    </BaseLayout>
  );
});

// playgrounds/router/routes/(vue3)/streaming/vue3-error@route.vue
<script setup lang="ts">
import { h } from 'vue';
import { defineRouteHandler } from '@web-widget/helpers';
import '~/routes/(css)/demo-states.css';
import BaseLayout from '../BaseLayout.vue';
import VueWaitDemo from '../Wait@widget.vue';
import VueFailDemo from '../Fail@widget.vue';

const Loading = h('div', { class: 'demo-loading' }, 'Loading..');
const ErrorFallback = h(
  'div',
  { class: 'demo-error' },
  'Widget failed to render (error recovered)'
);

defineOptions({
  handler: defineRouteHandler({
    async GET(ctx) {
      return ctx.html(undefined, { renderer: { progressive: true } });
    },
  }),
});
</script>

<template>
  <BaseLayout>
    <header class="ds-page-header">
      <h1>Vue3: Streaming error</h1>
      <p class="ds-description">
        This page demonstrates streaming SSR error recovery. The failing widget
        is wrapped in an onErrorCaptured boundary so the rest of the page stays
        functional.
      </p>
    </header>

    <section class="ds-section">
      <h2>Normal widget (succeeds)</h2>
      <VueWaitDemo :widget="{ fallback: Loading }" id="ok:0" />
    </section>

    <section class="ds-section">
      <h2>Failing widget with differentiated fallback (loading vs error)</h2>
      <VueFailDemo
        :widget="{ fallback: { pending: Loading, error: ErrorFallback } }"
        id="fail:0" />
    </section>

    <section class="ds-section">
      <h2>Another normal widget after the failure</h2>
      <VueWaitDemo :widget="{ fallback: Loading }" id="ok:1" />
    </section>
  </BaseLayout>
</template>
