// playgrounds/router/routes/(vue2)/vue2-server-component@route.vue
<script lang="ts">
import BaseLayout from './BaseLayout.vue';
import { mergeMeta, defineMeta, defineRouteHandler } from '@web-widget/helpers';

type PageData = {
  message: string;
};

export default {
  ...{
    meta: defineMeta({
      title: 'Vue2: Server component',
    }),
    handler: defineRouteHandler<PageData>({
      async GET(ctx) {
        return ctx.html(
          {
            message: 'This is the server component of vue.',
          },
          {
            meta: mergeMeta(ctx.meta, {
              description: 'vue2 examples',
            }),
          }
        );
      },
    }),
  },
};
</script>

<script setup lang="ts">
const props = defineProps({
  data: Object,
});
</script>

<template>
  <BaseLayout>
    <h1>Vue2: Server component</h1>
    <p class="data">{{ props.data }}</p>
  </BaseLayout>
</template>

<style>
.data {
  color: cadetblue;
}
</style>

// playgrounds/router/routes/react-server-component@route.tsx
import { defineRouteComponent } from '@web-widget/helpers';
import BaseLayout from './(components)/BaseLayout';
import { PageHeader } from './(components)/ui';

export default defineRouteComponent(function Page() {
  return (
    <BaseLayout>
      <PageHeader
        title="React: Server component"
        description="This is the server component of react."
      />
    </BaseLayout>
  );
});
