// packages/solid/src/adapter.client.ts
import { defineClientRender } from '@web-widget/helpers';
import type { Component } from 'solid-js';
import { createComponent } from 'solid-js';
import { hydrate, render as renderComponent } from 'solid-js/web';
export * from './components';

export const render = defineClientRender<Component<any>>(
  async (component, data, { container, recovering }) => {
    if (!component) throw new TypeError('Missing component.');
    if (!container) throw new Error('Missing container.');
    let dispose: (() => void) | undefined;
    return {
      mount() {
        const view = () => createComponent(component, data ?? {});
        const canHydrate = recovering && Reflect.has(globalThis, '_$HY');
        if (canHydrate) {
          dispose = hydrate(view, container);
        } else {
          container.replaceChildren();
          dispose = renderComponent(view, container);
        }
      },
      unmount() {
        dispose?.();
        dispose = undefined;
      },
    };
  }
);

// packages/react/src/adapter.client.ts
import { defineClientRender } from '@web-widget/helpers';
import type { FunctionComponent } from 'react';
import { createElement, StrictMode } from 'react';
import type { Root } from 'react-dom/client';
import { createRoot, hydrateRoot } from 'react-dom/client';

export * from '@web-widget/helpers';
export * from './components';

export const render = defineClientRender<FunctionComponent>(
  async (component, data, { recovering, container }) => {
    data = data ?? {};

    if (!component) {
      throw new TypeError(`Missing component.`);
    }

    if (!container) {
      throw new Error(`Missing container.`);
    }

    let root: Root | null;
    return {
      async mount() {
        const isAsyncFunction =
          Object.prototype.toString.call(component) ===
          '[object AsyncFunction]';
        let vNode = isAsyncFunction
          ? await component(data as any)
          : createElement(component as FunctionComponent, data as any);

        vNode = createElement(StrictMode, null, vNode);

        if (recovering) {
          root = hydrateRoot(container as Element, vNode as any);
        } else {
          root = createRoot(container);
          root.render(vNode as any);
        }
      },

      async unmount() {
        root?.unmount();
        root = null;
      },
    };
  }
);
