// examples/react-and-vue2/widgets/Counter.tsx
import "./counter-common.css";
import { useState } from "react";

interface CounterProps {
  name: string;
  start: number;
}

export default function Counter(props: CounterProps) {
  const [count, setCount] = useState(props.start);
  return (
    <div className="counter" title={props.name}>
      <button onClick={() => setCount(count - 1)}>-1</button>
      <span className="count">{count}</span>
      <button onClick={() => setCount(count + 1)}>+1</button>
    </div>
  );
}

// examples/web-server/components/Counter.vue
<script setup lang="ts">
import { ref } from 'vue';
const props = defineProps(['name', 'start']);

const name = props.name;
const count = ref(props.start);
</script>

<template>
  <div>
    <h3>{{ name }}</h3>
      <p>{{ count }}</p>
      <button @click="count--">
        -1
      </button>
      <button @click="count++">
        +1
      </button>
  </div>
</template>
