// examples/vue2/components/BaseLayout.tsx
import "../css/base-layout.css";

import type { ComponentProps } from "react";
import Menu from "../widgets/Menu.vue";

export default function BaseLayout({ children }: ComponentProps<any>) {
  return (
    <>
      <header>
        <h1>Web Router Examples</h1>
      </header>
      <div className="container">
        <aside>
          <Menu renderStage="server" />
        </aside>
        <main>{children}</main>
      </div>
      <footer>
        <p>This is a footer</p>
      </footer>
    </>
  );
}

// examples/react-and-vue2/components/BaseLayout.vue
<script setup lang="ts">
import "../css/base-layout.css";
import Menu from "../widgets/Menu.vue";
</script>
<template>
    <div>
      <header>
        <h1>Web Router Examples</h1>
      </header>
      <div class="container">
      <aside>
        <Menu renderStage="server" />
      </aside>
      <main><slot></slot></main>
    </div>
    <footer>
      <p>This is a footer</p>
    </footer>
    </div>
</template>
