// examples/web-server/components/Counter.vue
<script setup lang="ts">
import { ref } from 'vue';
const props = defineProps(['name', 'start']);

const name = props.name;
const count = ref(props.start);
</script>

<template>
  <div>
    <h3>{{ name }}</h3>
      <p>{{ count }}</p>
      <button @click="count--">
        -1
      </button>
      <button @click="count++">
        +1
      </button>
  </div>
</template>

// examples/koa-example/islands/Counter.tsx
import { useState } from "react";
export { render } from '@web-widget/react';

interface CounterProps {
  name: string;
  start: number;
}

export default function Counter(props: CounterProps) {
  const [count, setCount] = useState(props.start);
  return (
    <div>
      <h3>{props.name}</h3>
      <p>{count}</p>
      <button onClick={() => setCount(count - 1)}>
        -1
      </button>
      <button onClick={() => setCount(count + 1)}>
        +1
      </button>
    </div>
  );
}
