// packages/react/src/components.ts
import type { Loader, WebWidgetRendererOptions } from '@web-widget/web-widget';
import { WebWidgetRenderer } from '@web-widget/web-widget';
import { Suspense, createElement, use, memo } from 'react';
import type { FunctionComponent, ReactNode } from 'react';

export interface ReactWidgetComponent<T>
  extends FunctionComponent<T & WebWidgetSuspenseProps> {}

export interface WebWidgetProps {
  base?: WebWidgetRendererOptions['base'];
  children /**/?: ReactNode;
  data?: WebWidgetRendererOptions['data'];
  import?: WebWidgetRendererOptions['import'];
  inactive?: WebWidgetRendererOptions['inactive'];
  loader /**/ : Loader;
  meta?: WebWidgetRendererOptions['meta'];
  loading?: WebWidgetRendererOptions['loading'];
  name?: WebWidgetRendererOptions['name'];
  renderStage?: WebWidgetRendererOptions['renderStage'];
  renderTarget?: WebWidgetRendererOptions['renderTarget'];
}

interface WebWidgetElement {
  localName: string;
  attributes: Record<string, string>;
  innerHTML: Promise<string>;
}

const renderWebWidget = function ({
  children,
  loader,
  ...props
}: WebWidgetProps): WebWidgetElement {
  if (!loader) {
    throw new TypeError(`Missing loader.`);
  }

  if (children) {
    throw new TypeError(`Children not supported.`);
  }

  const widget = new WebWidgetRenderer(loader as Loader, {
    ...props,
    // TODO children
    children: '',
  });
  const localName = widget.localName;
  const attributes = widget.attributes;
  const innerHTML = widget.renderInnerHTMLToString();
  return {
    localName,
    attributes,
    innerHTML,
  };
};

function WebWidget({ localName, attributes, innerHTML }: WebWidgetElement) {
  const html = use(innerHTML);
  return createElement(localName, {
    ...attributes,
    dangerouslySetInnerHTML: { __html: html },
    // NOTE: Since the innerHTML property of a widget
    // will inevitably differ between the server and the client,
    // this turns off hydration mismatch warnings.
    suppressHydrationWarning: true,
  });
}

export type DefineWebWidgetOptions = Partial<
  Pick<
    WebWidgetRendererOptions,
    'base' | 'import' | 'loading' | 'name' | 'renderStage' | 'renderTarget'
  >
>;

export interface WebWidgetSuspenseProps {
  children?: ReactNode;
  fallback?: ReactNode;
  experimental_loading?: WebWidgetRendererOptions['loading'];
  renderStage?: WebWidgetRendererOptions['renderStage'];
  experimental_renderTarget?: WebWidgetRendererOptions['renderTarget'];
}

export /*#__PURE__*/ function defineWebWidget(
  loader: Loader,
  options: DefineWebWidgetOptions
) {
  return memo(function WebWidgetSuspense({
    children,
    fallback,
    experimental_loading = options.loading ?? 'lazy',
    renderStage = options.renderStage,
    experimental_renderTarget = options.renderTarget ?? 'light',
    ...data
  }: WebWidgetSuspenseProps) {
    return createElement(Suspense, {
      fallback,
      children: createElement(
        WebWidget,
        renderWebWidget({
          ...options,
          children,
          data,
          loader,
          loading: experimental_loading,
          renderStage,
          renderTarget: experimental_renderTarget,
        })
      ),
    });
  });
}

// packages/solid/src/components.ts
import type { Component, JSX } from 'solid-js';
import {
  ErrorBoundary,
  Suspense,
  createComponent,
  createResource,
  splitProps,
} from 'solid-js';
import { Dynamic } from 'solid-js/web';
import type { Loader, WebWidgetRendererOptions } from '@web-widget/web-widget';
import type { ExtractWidgetProps } from '@web-widget/schema';
import { WebWidgetRenderer } from '@web-widget/web-widget';

export type DefineWebWidgetOptions = Partial<
  Pick<
    WebWidgetRendererOptions,
    'base' | 'import' | 'loading' | 'name' | 'renderStage' | 'renderTarget'
  >
>;

export interface WidgetContainerConfig {
  fallback?: JSX.Element | { pending?: JSX.Element; error?: JSX.Element };
  loading?: WebWidgetRendererOptions['loading'];
  serverOnly?: true;
  clientOnly?: true;
}

export type SolidWidgetComponent<T = unknown> = Component<
  T & { children?: JSX.Element; widget?: WidgetContainerConfig }
>;

function resolveFallback(fallback: WidgetContainerConfig['fallback']): {
  pending: JSX.Element;
  error: JSX.Element;
} {
  if (
    fallback !== null &&
    typeof fallback === 'object' &&
    ('pending' in fallback || 'error' in fallback)
  ) {
    return {
      pending: fallback.pending,
      error: fallback.error ?? fallback.pending,
    };
  }
  return { pending: fallback as JSX.Element, error: fallback as JSX.Element };
}

export function container<M>(
  loader: () => Promise<M>,
  options?: DefineWebWidgetOptions
): SolidWidgetComponent<ExtractWidgetProps<M>>;
export function container<Props>(
  loader: Loader,
  options?: DefineWebWidgetOptions
): SolidWidgetComponent<Props>;
export function container(
  loader: Loader,
  options: DefineWebWidgetOptions = {}
) {
  return ((props: Record<string, any>) => {
    const [local, data] = splitProps(props, ['children', 'widget']);
    if (local.children) throw new TypeError('Children not supported.');
    const widget = local.widget ?? {};
    const fallback = resolveFallback(widget.fallback);
    const renderStage = widget.serverOnly
      ? 'server'
      : widget.clientOnly
        ? 'client'
        : options.renderStage;
    const renderer = new WebWidgetRenderer(loader, {
      ...options,
      children: '',
      data,
      loading: widget.loading ?? options.loading ?? 'lazy',
      renderStage,
      renderTarget: options.renderTarget ?? 'light',
    });
    const [html] = createResource(() => renderer.renderInnerHTMLToString());
    const content = () =>
      createComponent(Dynamic, {
        component: renderer.localName,
        ...renderer.attributes,
        get innerHTML() {
          return html();
        },
      });
    return createComponent(ErrorBoundary, {
      fallback: () => fallback.error,
      get children() {
        return createComponent(Suspense, {
          fallback: fallback.pending,
          get children() {
            return content();
          },
        });
      },
    });
  }) as SolidWidgetComponent<any>;
}
