// examples/vue/routes/greet/[name]@route.vue
<script setup lang="ts">
import { defineMeta } from '@web-widget/helpers';
import BaseLayout from '../(components)/BaseLayout.vue';

interface Params {
  name: string;
}

defineOptions({
  meta: defineMeta({
    title: 'Dynamic routes - Web Widget',
  }),
});

const { params } = defineProps<{ params: Params }>();
</script>

<template>
  <BaseLayout>
    <h1>Dynamic routes</h1>
    <p>Greetings to you, {{ params.name }}!</p>
    <p>
      <a href="/greet/react">react</a>
    </p>
    <p>
      <a href="/greet/vue">vue</a>
    </p>
  </BaseLayout>
</template>

// playgrounds/router/routes/dynamic-routes/[name]@route.tsx
import { defineRouteComponent } from '@web-widget/helpers';
import BaseLayout from '../(components)/BaseLayout';

export default defineRouteComponent(function Page(props) {
  const { name } = props.params;
  return (
    <BaseLayout>
      <h1>Dynamic routes</h1>
      <p>Greetings to you, {JSON.stringify(name)}!</p>
      <ul>
        <li>
          <a href="/dynamic-routes/web-route">web-route</a>
        </li>
        <li>
          <a href="/dynamic-routes/builder">builder</a>
        </li>
        <li>
          <a href="/dynamic-routes/react">react</a>
        </li>
        <li>
          <a href="/dynamic-routes/vue">vue</a>
        </li>
        <li>
          <a href="/dynamic-routes/html">html</a>
        </li>
      </ul>
    </BaseLayout>
  );
});
