// playgrounds/router/routes/(components)/preact/Counter@widget.tsx
/** @jsxImportSource preact */
import { useState } from 'preact/hooks';
import styles from '~/routes/(css)/counter.module.css';

export default function Counter({
  count: initialCount = 0,
}: {
  count?: number;
}) {
  const [count, setCount] = useState(initialCount);
  return (
    <button class={styles.button} onClick={() => setCount(count + 1)}>
      Preact count is {count}
    </button>
  );
}

// playgrounds/router/routes/frameworks/solid/Counter@widget.tsx
/** @jsxImportSource solid-js */
import { createSignal } from 'solid-js';
import styles from '~/routes/(css)/counter.module.css';

export default function Counter(props: { count?: number }) {
  const [count, setCount] = createSignal(props.count ?? 0);
  return (
    <button class={styles.button} onClick={() => setCount(count() + 1)}>
      Solid count is {count()}
    </button>
  );
}
