// playgrounds/router/routes/_404@route.tsx
import './(css)/error.css';
import { defineRouteFallbackComponent } from '@web-widget/helpers';
import { container } from '@web-widget/react/adapter';

const RVueCounter = container(
  () => import('@playgrounds/web-router-vue3/Counter@widget.vue')
);

const Page404 = defineRouteFallbackComponent(function Page404(ctx) {
  return (
    <main>
      <div className="error-card">
        <p className="error-code error-code-404">404</p>
        <p className="error-title">Page Not Found</p>
        {ctx.message && <pre className="error-message">{ctx.message}</pre>}
        <RVueCounter count={3} />
        <p style={{ marginTop: '24px' }}>
          <a className="error-home" href="/">
            Back to Home
          </a>
        </p>
      </div>
    </main>
  );
});

export { Page404 as fallback };
export default Page404;

// examples/vue/routes/_404@route.vue
<script lang="ts">
import { defineMeta, defineRouteFallbackComponent } from '@web-widget/helpers';
import BaseLayout from './examples/(components)/BaseLayout.vue';
import ErrorPage from './examples/(components)/ErrorPage.vue';
import shared from './examples/(components)/shared.module.css';
import { h } from 'vue';

export const meta = defineMeta({
  title: 'Not Found',
});

export const fallback = defineRouteFallbackComponent(function Page() {
  return h(BaseLayout, {}, [
    h('div', { class: shared.container }, [
      h(ErrorPage)
    ])
  ]);
});
</script>

<template>
  <!-- This route uses the fallback component defined above -->
</template>
